name: Python CI

on:
  push:
    branches:
      - dev

jobs:
  security-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Checkov
        run: |
          pip install checkov

      - name: Run Checkov Security Scan
        run: |
          checkov -d .

  lint:
    runs-on: ubuntu-latest
    needs: security-check
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Pylint
        run: |
          pip install pylint
          pylint $(git ls-files '*.py')
